*** Variables ***
${locator_info_facility} =                  //p[@id="facility"]
${locator_info_apply_readmission} =         //p[@id="hospital_readmission"]
${locator_info_healthcare_program} =        //p[@id="program"]
${locator_info_visit_date} =                //p[@id="visit_date"]
${locator_info_comment} =                   //p[@id="comment"]
${locator_button_go_homepage} =             //a[@class="btn btn-default" and text()="Go to Homepage"]