*** Variables ***
${locator_button_make_appointment} =    //a[@id='btn-make-appointment']
${locator_button_menu} =                //a[@id='menu-toggle']
${locator_button_menu_login} =          //a[@href='profile.php#login']
${locator_button_menu_logout} =         //a[@href='authenticate.php?logout']
${locator_button_menu_history} =         //a[@href='history.php#history']
${locator_button_menu_home} =           //a[@href='./']