*** Variables ***
${locator_select_facility} =            //select[@id='combo_facility']
${locator_checkbox_readmission} =       //input[@id="chk_hospotal_readmission"]
${locator_radio_program}=               //input[@name="programs"]
${locator_input_visit_date} =           //input[@id="txt_visit_date"]
${locator_input_comment} =              //textarea[@id="txt_comment"]
${locator_button_book_appointment} =    //button[@id="btn-book-appointment"]
${locator_error_message_invalid_visit_date} =    //p[@id="message-invalid-visit-date"]